### ISSUE TITLE
Hi my friend

### ISSUE THREAD

**Issue by Happyclem** [jakeledoux/clem2#2]
Hello Jake,

I was cleaning my internet footprint when I found my old itch.io account.
I made my friend play fallout simulator for a bit saying I helped for this game translation.
A couple minutes later he send me a link to your github and this project.

I am stunned, and humbled that this project is named after my contribution.

Not an issue here, just saying hello ! 

Also, I see a fallout simulator v2 in the work, i'll gladly play that game ;)

Lot of loves !

Edit : There is *some* errors in what I did in the original game, i'm so sorry x) Can adjust that now.

**Comment by jakeledoux** [comment]
Haha I thought you'd get a kick out of this one. I had to name it something and this was easy for me to remember.

Maybe I'll port this project to Rust sometime! Cheers.
